spring.application.name=product-service
server.port=8082
    jwt.secret=Y29tZSBvbiBzaGl2YSB0aGlzIGlzIGEgc3VwZXIgc2VjcmV0IGtleSBmb3IgSldU
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000